title: Lucky Lim
description: 
  Agile Software Developer (4 years experience)
  
  Strong Analytical Individual, Clean Code Practitioner, and Passionate Technologist
google_analytics: 
show_downloads: false
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
