title: Lucky Lim
description: 
  About me<br/>
  - Java Developer in Finance Sector (4 years experience)<br/>
  - Clean, Highly Testable Code<br/>
  - Analytics and enjoy problem solving<br/><br/>
  Find me<br/>
  - (http://limluc.github.io/)<br/>
  - (http://stackoverflow.com/users/7675608/lucky-lim)<br/>
  - (https://www.hackerrank.com/limluc)<br/>
  - (https://www.linkedin.com/in/luckylim/)<br/><br/>
  Contact<br/>
  London, United Kingdom<br/>
  Mobile: (44) 793 879 7117<br/>
  Email: lucky.lim@me.com<br/>
  LinkedIn: uk.linkedin.com/in/luckylim<br/>
  Github: github.com/limluc
google_analytics: 
show_downloads: false
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
