title: Lucky Lim
description: 
  
  About me:
  
  - Java Developer in Finance Sector (4 years experience)
  - Programing stye: Clean, Highly Testable Code
  - Analytics and enjoy problem solving
  
  Find me:
  
  - http://limluc.github.io/
  - http://stackoverflow.com/users/7675608/lucky-lim
  - https://www.hackerrank.com/limluc
  - https://www.linkedin.com/in/luckylim/
  
google_analytics: 
show_downloads: false
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
