title: Lucky Lim
description: 
  <b>About me</b><br/>
  Agile Sofware Developer<br/>
  Strong Analytical Individual, Clean Code Practitioner, and Passionate Technologist<br/><br/>
  <b>Skills</b><br/>
  <b>Professionally</b><br/>
  Java 7/8, Spring, Gemfire, ELK,  Cucumber, SQL, Git/SVN, Maven, Linux<br/>
  <b>Some Experience</b><br/>
  Scala, Clojure, Groovy, Python, PHP, VBA<br/><br/>
  <b>Projects</b><br/>
  See [limluc.io](https://github.com/limluc/limluc.github.io/blob/master/README.md)<br/><br/>
  <b>Contact</b><br/>
  London, United Kingdom<br/>
  Mobile (44) 793 879 7117<br/>
  Email <a href="mailto:lucky.lim@me.com">lucky.lim@me.com</a><br/>
  <a href="http://limluc.github.io">GitHub/luckylim</a><br/>
  <a href="http://stackoverflow.com/users/7675608/lucky-lim">StackOverflow/luckylim</a><br/>
  <a href="https://www.hackerrank.com/limluc">HackerRank/luckylim</a><br/>
  <a href="https://www.linkedin.com/in/luckylim">LinkedIn/luckylim</a><br/><br/>
google_analytics: 
show_downloads: false
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
