title: Lucky Lim
description: 
  <b>About me</b><br/>
  Java Developer in Finance Sector (4 years experience)<br/>
  Clean, Highly Testable Code<br/>
  Analytics and enjoy problem solving<br/><br/>
  <b>Contact</b><br/>
  London, United Kingdom<br/>
  Mobile (44) 793 879 7117<br/>
  Email <a href="mailto:lucky.lim@me.com">lucky.lim</a><br/>
  <a href="http://limluc.github.io">Github</a><br/>
  <a href="http://stackoverflow.com/users/7675608/lucky-lim">StackOverflow</a><br/>
  <a href="https://www.hackerrank.com/limluc">HackerRank</a><br/>
  <a href="https://www.linkedin.com/in/luckylim">LinkedIn</a><br/><br/>
google_analytics: 
show_downloads: false
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
